/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;
/**
 * The main class that starts the program
 */
public class Library {
	/*
	 * Main function: all things start here
	 * Do not touch anything in this file
	 */
	/**
	 * main of the application
	 * @param args args for the main
	 */
    public static void main(String args[])
    {
    	UIApplication.run(args);
    }
}
